mock_qgenda_relevant_data = [{'StaffAbbrev': 'Loh', 'TaskName': 'RISK1'},
                             {'StaffAbbrev': 'N.Nguyen', 'TaskName': 'PTO/VACATION 1'},
                             {'StaffAbbrev': 'Gordon', 'TaskName': 'APP MD2'},
                             {'StaffAbbrev': 'Stuart', 'TaskName': 'APP MD1'},
                             {'StaffAbbrev': 'Rajneet', 'TaskName': 'PTO/VACATION 1'},
                             {'StaffAbbrev': 'Stuart', 'TaskName': 'AM TRIAGE'},
                             {'StaffAbbrev': 'Amrit', 'TaskName': 'DOC1'},
                             {'StaffAbbrev': 'KochLeibmann', 'TaskName': 'DOC3'},
                             {'StaffAbbrev': 'Siew', 'TaskName': 'DOC5'},
                             {'StaffAbbrev': 'Uselman', 'TaskName': 'DOC9'},
                             {'StaffAbbrev': 'Stuart', 'TaskName': 'DOC2'},
                             {'StaffAbbrev': 'Scott', 'TaskName': 'APP1'},
                             {'StaffAbbrev': 'Pelley', 'TaskName': 'DOC4'},
                             {'StaffAbbrev': 'Gordon', 'TaskName': 'DOC7'},
                             {'StaffAbbrev': 'Addison', 'TaskName': 'DOC84'},
                             {'StaffAbbrev': 'Kuo', 'TaskName': 'DOC6'},
                             {'StaffAbbrev': 'Siew', 'TaskName': 'PM TRIAGE'},
                             {'StaffAbbrev': 'Au', 'TaskName': 'PM ADMITTER'},
                             {'StaffAbbrev': 'Hines', 'TaskName': 'SWING'},
                             {'StaffAbbrev': 'Davis', 'TaskName': 'NIGHT'}]
